version: '3.8'

services:
  wake-on-lan:
    build: .
    ports:
      - "8000:8000"
    environment:
      - TARGET_MAC=${TARGET_MAC}
      - AUTH_USERNAME=${AUTH_USERNAME}
      - AUTH_PASSWORD=${AUTH_PASSWORD}
    restart: unless-stopped
    network_mode: "host"  # Required for Wake-on-LAN to work properly
